package lampas2overrides.mobfilter.mixin;

import com.llamalad7.mixinextras.injector.wrapmethod.WrapMethod;
import com.llamalad7.mixinextras.injector.wrapoperation.Operation;
import lampas2overrides.mobfilter.WorldgenDimensionContext;
import net.minecraft.resources.Identifier;
import net.minecraft.server.level.WorldGenRegion;
import net.minecraft.world.entity.Entity;

import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Redirect;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

/**
 * Scopes the active worldgen dimension and prevents Mob Filter's rejected worldgen entities
 * from running Entity.remove.
 *
 * <p>During world generation, Mob Filter cannot identify the dimension on its own and treats
 * {@code null} as matching any dimension check. Wrapping {@code WorldGenRegion_addFreshEntity}
 * installs the current dimension into {@link WorldgenDimensionContext} for the duration of the
 * check.
 *
 * <p>Additionally, the entity has not been admitted to the {@code WorldGenRegion}; Mob Filter's
 * existing {@code setReturnValue(false)} is sufficient to veto the insertion. Calling
 * {@code remove} first can enter dismount collision resolution and recursively request
 * the chunk currently being generated by a C2ME worker.
 */
@Mixin(targets = "net.pcal.mobfilter.MixinService", remap = false)
public final class MixinServiceMixin {

	@WrapMethod(method = "WorldGenRegion_addFreshEntity")
	private void lampas2$scopeWorldgenDimension(
			WorldGenRegion worldGenRegion,
			Entity entity,
			CallbackInfoReturnable<Boolean> cir,
			Operation<Void> original
	) {
		Identifier previous = WorldgenDimensionContext.get();
		try {
			WorldgenDimensionContext.set(worldGenRegion.getLevel().dimension().identifier());
			original.call(worldGenRegion, entity, cir);
		} finally {
			WorldgenDimensionContext.set(previous);
		}
	}

	@Redirect(
		method = "WorldGenRegion_addFreshEntity",
		at = @At(
			value = "INVOKE",
			target = "Lnet/minecraft/world/entity/Entity;remove(Lnet/minecraft/world/entity/Entity$RemovalReason;)V"
		),
		require = 1
	)
	private void lampas2$skipWorldgenDiscard(Entity entity, Entity.RemovalReason reason) {
		// The upstream callback still returns false immediately after this call site.
	}
}

