package lampas2overrides.mobfilter.mixin;

import net.minecraft.world.entity.Entity;

import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Redirect;

/**
 * Prevents Mob Filter's rejected worldgen entities from running Entity.remove.
 *
 * <p>The entity has not been admitted to the {@code WorldGenRegion}; Mob Filter's
 * existing {@code setReturnValue(false)} is sufficient to veto the insertion. Calling
 * {@code remove} first can enter dismount collision resolution and recursively request
 * the chunk currently being generated by a C2ME worker.
 */
@Mixin(targets = "net.pcal.mobfilter.MixinService", remap = false)
public final class MixinServiceMixin {

	@Redirect(
		method = "WorldGenRegion_addFreshEntity",
		at = @At(
			value = "INVOKE",
			target = "Lnet/minecraft/world/entity/Entity;remove(Lnet/minecraft/world/entity/Entity$RemovalReason;)V"
		),
		require = 1
	)
	private void lampas2$skipWorldgenDiscard(Entity entity, Entity.RemovalReason reason) {
		// The upstream callback still returns false immediately after this call site.
	}
}
